name: CD

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17', '19']

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.Java}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.Java}}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -DskipTests=true --file pom.xml

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: runner test
        run: mvn clean verify -X -DskipTests=true

  package:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: package application
        run: |
          mvn clean install -X -DskipTests=true
          mvn package -X -DskipTests=true
